[Xorg_damageproto]
git-tree-sha1 = "861d3b2420fcd2525d7ac67f0cf82eb3814f6c1c"

    [[Xorg_damageproto.download]]
    sha256 = "2f596bcb7aeb6fbc23a9aa60bdb2138c75913a0d502b256edb51002c0f68b803"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_damageproto_jll.jl/releases/download/Xorg_damageproto-v1.2.1+1/Xorg_damageproto.v1.2.1.any.tar.gz"
